import logging
from pathlib import Path
import faiss
import numpy as np

from embeddings.cache import load_embeddings

logger = logging.getLogger(__name__)

class FaissBuilder:
    """
    Builder for creating and managing FAISS indices for vector search.
    """
    
    @staticmethod
    def build_index(embeddings: np.ndarray, is_normalized: bool = True) -> faiss.IndexFlatIP:
        """
        Builds a FAISS IndexFlatIP (Inner Product) from embeddings.
        Assuming embeddings are normalized, Inner Product is equivalent to Cosine Similarity.
        
        Args:
            embeddings: A 2D NumPy array of embeddings.
            is_normalized: If False, normalizes the embeddings before adding to index.
            
        Returns:
            A populated FAISS IndexFlatIP.
        """
        if embeddings.ndim != 2:
            raise ValueError(f"Embeddings must be a 2D array, got {embeddings.ndim}D")
            
        dimension = embeddings.shape[1]
        logger.info(f"Building FAISS IndexFlatIP with dimension {dimension} and {embeddings.shape[0]} vectors.")
        
        index = faiss.IndexFlatIP(dimension)
        
        if not is_normalized:
            logger.info("Normalizing embeddings before adding to index...")
            faiss.normalize_L2(embeddings)
            
        index.add(embeddings)
        logger.info("Successfully built FAISS index.")
        return index

    @staticmethod
    def save_index(index: faiss.IndexFlatIP, file_path: Path) -> None:
        """
        Saves the FAISS index to disk.
        
        Args:
            index: The FAISS index to save.
            file_path: The path where to save the index.
        """
        try:
            file_path.parent.mkdir(parents=True, exist_ok=True)
            faiss.write_index(index, str(file_path))
            logger.info(f"Successfully saved FAISS index to {file_path}")
        except Exception as e:
            logger.error(f"Failed to save FAISS index to {file_path}: {e}")
            raise

    @staticmethod
    def load_index(file_path: Path) -> faiss.IndexFlatIP:
        """
        Loads the FAISS index from disk.
        
        Args:
            file_path: The path to the saved index.
            
        Returns:
            The loaded FAISS index.
        """
        if not file_path.exists():
            raise FileNotFoundError(f"FAISS index file not found: {file_path}")
            
        try:
            index = faiss.read_index(str(file_path))
            logger.info(f"Successfully loaded FAISS index from {file_path}")
            return index
        except Exception as e:
            logger.error(f"Failed to load FAISS index from {file_path}: {e}")
            raise

    @staticmethod
    def build_and_save_from_cache(embeddings_path: Path, index_path: Path) -> None:
        """
        Loads embeddings from cache, builds the index, and saves it.
        
        Args:
            embeddings_path: Path to the .npy embeddings file.
            index_path: Path to save the .index file.
        """
        logger.info(f"Building FAISS index from cached embeddings at {embeddings_path}")
        embeddings = load_embeddings(embeddings_path)
        
        # We assume embeddings generated by our generator are already normalized, 
        # but FaissBuilder handles it just in case if needed. We'll pass True here.
        index = FaissBuilder.build_index(embeddings, is_normalized=True)
        
        FaissBuilder.save_index(index, index_path)
